# server:
#   port: ${PORT:8080}
#   servlet:
#     context-path: /api
#   tomcat:
#     max-threads: 200
#     accept-count: 100
#     connection-timeout: 30000

# spring:
#   application:
#     name: leboncoin-clone
  
#   datasource:
#     url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:leboncoin_prod}
#     username: ${DB_USER:appuser}
#     password: ${DB_PASSWORD:StrongPasswordHere}
#     driver-class-name: org.postgresql.Driver
#     hikari:
#       connection-timeout: 30000
#       maximum-pool-size: 50
#       minimum-idle: 10
#       idle-timeout: 600000
#       max-lifetime: 1800000
  
#   jpa:
#     hibernate:
#       ddl-auto: none  
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.PostgreSQLDialect
#         format_sql: false
#         show_sql: false
#     open-in-view: false