spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: traore
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: dt2040760@gmail.com
    password: nhoqdgcmdkrxxzsg
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true

logging:
  level:
    root: info
    org.springframework:
      web: DEBUG
      validation: DEBUG
  file:
    name: logs/application.log

security:
  basic:
    enabled: false 
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000 # 1 heure en millisecondes

  oauth2:
    client:
      registration:
        google:
          client-id: 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
          client-secret: 88111138112-fkgisda7ql2mjmr6ov73ft4b15bo0g6v.apps.googleusercontent.com
          scope:
            - email
            - profile

app:
  name: "MALI SUGU"
  description: "Une application Spring Boot connectée à une base de données PostgreSQL"
